/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedDiaryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canDecryptEntry"
      | "canUnlockEntry"
      | "createEntry"
      | "getEncryptedEntry"
      | "getEntryCount"
      | "getEntryMetadata"
      | "getUserEntries"
      | "getUserEntryCount"
      | "protocolId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "EntryCreated" | "EntryUnlocked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canDecryptEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canUnlockEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEntry",
    values: [BytesLike, BytesLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryMetadata",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserEntries",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserEntryCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "canDecryptEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canUnlockEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntryMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserEntries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
}

export namespace EntryCreatedEvent {
  export type InputTuple = [
    entryId: BigNumberish,
    author: AddressLike,
    unlockTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    entryId: bigint,
    author: string,
    unlockTimestamp: bigint
  ];
  export interface OutputObject {
    entryId: bigint;
    author: string;
    unlockTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntryUnlockedEvent {
  export type InputTuple = [entryId: BigNumberish];
  export type OutputTuple = [entryId: bigint];
  export interface OutputObject {
    entryId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedDiary extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedDiary;
  waitForDeployment(): Promise<this>;

  interface: EncryptedDiaryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canDecryptEntry: TypedContractMethod<
    [entryId: BigNumberish],
    [boolean],
    "view"
  >;

  canUnlockEntry: TypedContractMethod<
    [entryId: BigNumberish],
    [boolean],
    "view"
  >;

  createEntry: TypedContractMethod<
    [
      encryptedContent: BytesLike,
      inputProof: BytesLike,
      unlockTimestamp: BigNumberish,
      isPublic: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  getEncryptedEntry: TypedContractMethod<
    [entryId: BigNumberish],
    [string],
    "view"
  >;

  getEntryCount: TypedContractMethod<[], [bigint], "view">;

  getEntryMetadata: TypedContractMethod<
    [entryId: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        author: string;
        createdAt: bigint;
        unlockTimestamp: bigint;
        isPublic: boolean;
      }
    ],
    "view"
  >;

  getUserEntries: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  getUserEntryCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canDecryptEntry"
  ): TypedContractMethod<[entryId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "canUnlockEntry"
  ): TypedContractMethod<[entryId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "createEntry"
  ): TypedContractMethod<
    [
      encryptedContent: BytesLike,
      inputProof: BytesLike,
      unlockTimestamp: BigNumberish,
      isPublic: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedEntry"
  ): TypedContractMethod<[entryId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEntryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEntryMetadata"
  ): TypedContractMethod<
    [entryId: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        author: string;
        createdAt: bigint;
        unlockTimestamp: bigint;
        isPublic: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserEntries"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserEntryCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "EntryCreated"
  ): TypedContractEvent<
    EntryCreatedEvent.InputTuple,
    EntryCreatedEvent.OutputTuple,
    EntryCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EntryUnlocked"
  ): TypedContractEvent<
    EntryUnlockedEvent.InputTuple,
    EntryUnlockedEvent.OutputTuple,
    EntryUnlockedEvent.OutputObject
  >;

  filters: {
    "EntryCreated(uint256,address,uint256)": TypedContractEvent<
      EntryCreatedEvent.InputTuple,
      EntryCreatedEvent.OutputTuple,
      EntryCreatedEvent.OutputObject
    >;
    EntryCreated: TypedContractEvent<
      EntryCreatedEvent.InputTuple,
      EntryCreatedEvent.OutputTuple,
      EntryCreatedEvent.OutputObject
    >;

    "EntryUnlocked(uint256)": TypedContractEvent<
      EntryUnlockedEvent.InputTuple,
      EntryUnlockedEvent.OutputTuple,
      EntryUnlockedEvent.OutputObject
    >;
    EntryUnlocked: TypedContractEvent<
      EntryUnlockedEvent.InputTuple,
      EntryUnlockedEvent.OutputTuple,
      EntryUnlockedEvent.OutputObject
    >;
  };
}
